baseURL: 'https://cascodes.de/'
languageCode: 'en-us'
title: 'CasCodes'
theme: "PaperMod"
defaultTeme: dark

enableEmoji: true
tag: "tags"

# top menu
menu:
  main:
  - name: about
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: -110
  - name: home
    pre: <i class='fa fa-road'></i>
    url: /
    weight: -100

params:
    profileMode:
        enabled: true
        Title: Hi there! âœŒï¸
        subtitle: ğŸ§  AI + Web ğŸ Python â¤ï¸ Open source
        imageUrl: icon.png 
        imageWidth: 150 # custom size
        imageHeight: 150 # custom size
        buttons: # center
          - name: Projects
            url: "/projects/"
          - name: Github
            url: "https://github.com/CasCodes"

